services:
  mysql:
    image: mysql:8.4
    container_name: prometeo-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prometeo
    ports:
      - "3306:3306"
    volumes:
      - ../sql:/docker-entrypoint-initdb.d

